name: Docker

on:
  workflow_call:
    inputs:
      dockerhub-username:
        required: true
        type: string
        description: The hub.docker.com username under which the image should be published.
      tag:
        required: false
        default: latest
        type: string
        description: The tag for the built image.
      tag-buildarg:
        required: false
        default: TAG
        type: string
        description: The dockerfile's buildarg which contains the target tag.
      build-cache:
        required: false
        default: true
        type: boolean
        description: If enabled, a build cache will be attached to the docker build process.
    secrets:
      dockerhub-token:
        description: The token used to authenticate with hub.docker.com.
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REGISTRY_IMAGE: ${{ inputs.dockerhub-username }}/${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        platform: ["linux/amd64", "linux/arm64", "linux/arm/v6", "linux/arm/v7"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,${{ inputs.tag }}
            type=sha,enable=true,priority=100,prefix=${{ inputs.tag }}-,suffix=,format=short

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ inputs.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}
          
      - name: Setup Go Build Cache for Docker
        if: ${{ inputs.build-cache }}
        uses: actions/cache@v4
        with:
          path: build-cache
          key: ${{ inputs.tag }}-${{ matrix.platform }}-build-cache

      - name: Inject go-build-cache into Docker
        if: ${{ inputs.build-cache }}
        uses: reproducible-containers/buildkit-cache-dance@v2
        with:
          cache-source: build-cache

      - name: Build
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          push: false
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: ${{ inputs.tag-buildarg }}=${{ inputs.tag }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
          sbom: true

      - name: Export Digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload Digest
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.tag }}-digests
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download Digests
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.tag }}-digests
          path: /tmp/digests

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,${{ inputs.tag }}
            type=sha,enable=true,priority=100,prefix=${{ inputs.tag }}-,suffix=,format=short

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Manifest List and Push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
          
      - name: Push Image to GHCR
        run: |
          docker buildx imagetools create \
            --tag ghcr.io/${{ env.REGISTRY_IMAGE }}:${{ inputs.tag }} \
            ${{ env.REGISTRY_IMAGE }}:${{ inputs.tag }}

      - name: Inspect Image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ inputs.tag }}

