name: test

on:
  - workflow_dispatch
  - workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: upstream
        run: |
          git remote -v

